# Generated by Django 4.2.4 on 2023-08-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_platform', models.CharField(max_length=50, unique=True)),
                ('about', models.CharField(max_length=200)),
                ('website', models.URLField(unique=True)),
            ],
        ),
    ]
